### ISSUE TITLE
Rotated images

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#2]
I'm still seeing images that shouldn't be rotated, see attached pictures. The only rotated images should be BOARDS.
![screenshot 2015-06-10 09 58 02](https://cloud.githubusercontent.com/assets/3596525/8082941/861d010e-0f57-11e5-8514-e3309f1bd509.png)
![screenshot 2015-06-10 09 57 56](https://cloud.githubusercontent.com/assets/3596525/8082942/86408322-0f57-11e5-80fa-f60c881d3810.png)
![screenshot 2015-06-10 09 57 49](https://cloud.githubusercontent.com/assets/3596525/8082943/86549790-0f57-11e5-9bb0-792c2c4fef4a.png)

**Comment by mediamilan** [comment]
Because both parent and child category are selected its impossible to rate images just based on categories. So here is a place which you can select to rate any image that you think is good.

![banners_and_alerts_and_edit_product_ _open_box_store_ _wordpress](https://cloud.githubusercontent.com/assets/2662306/8127426/62655338-1114-11e5-830b-67033c6e67b5.png)

**Comment by mediamilan** [comment]
![open_box_store___product_categories___longboard](https://cloud.githubusercontent.com/assets/2662306/8127553/7cfd143c-1115-11e5-8572-de30c29b0e4e.png)
